# Generated by Django 4.2.3 on 2024-01-22 12:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='product_status',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=core.models.user_directory_path),
        ),
    ]
