# Generated by Django 4.2.3 on 2024-01-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cartorder_product_status_cartorder_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='image',
        ),
        migrations.AlterField(
            model_name='cartorderproducts',
            name='image',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
