# Generated by Django 4.2.3 on 2024-01-22 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_cartorder_image_alter_cartorderproducts_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='specifications',
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.IntegerField(blank=True, default='none', null=True),
        ),
    ]
